models/Absen.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "dst_absen".
 *
 * @property string $absen_id
 * @property string $fk_siswa_id
 * @property string $fk_kelas_id
 * @property string $fk_jurusan_id
 * @property string $fk_mapel_id
 * @property string $absen_keterangan
 * @property string $absen_tanggal
 *
 * @property Jurusan $fkJurusan
 * @property Kelas $fkKelas
 * @property Mapel $fkMapel
 * @property Siswa $fkSiswa
 */
class Absen extends \yii\db\ActiveRecord {
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'dst_absen';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['fk_siswa_id', 'fk_kelas_id', 'fk_jurusan_id', 'fk_mapel_id', 'absen_tanggal'], 'required'],
            [['fk_siswa_id', 'fk_kelas_id', 'fk_jurusan_id', 'fk_mapel_id'], 'integer'],
            [['absen_keterangan'], 'string'],
            [['absen_tanggal'], 'safe'],
            [['fk_jurusan_id'], 'exist', 'skipOnError' => true, 'targetClass' => Jurusan::className(), 'targetAttribute' => ['fk_jurusan_id' => 'jurusan_id']],
            [['fk_kelas_id'], 'exist', 'skipOnError' => true, 'targetClass' => Kelas::className(), 'targetAttribute' => ['fk_kelas_id' => 'kelas_id']],
            [['fk_mapel_id'], 'exist', 'skipOnError' => true, 'targetClass' => Mapel::className(), 'targetAttribute' => ['fk_mapel_id' => 'mapel_id']],
            [['fk_siswa_id'], 'exist', 'skipOnError' => true, 'targetClass' => Siswa::className(), 'targetAttribute' => ['fk_siswa_id' => 'siswa_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'absen_id' => 'Absen ID',
            'fk_siswa_id' => 'Nama Siswa',
            'fk_kelas_id' => 'Kelas',
            'fk_jurusan_id' => 'Jurusan',
            'fk_mapel_id' => 'Mata Pelajaran',
            'absen_keterangan' => 'Keterangan',
            'absen_tanggal' => 'Tanggal',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJurusan() {
        return $this->hasOne(Jurusan::className(), ['jurusan_id' => 'fk_jurusan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKelas() {
        return $this->hasOne(Kelas::className(), ['kelas_id' => 'fk_kelas_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMapel() {
        return $this->hasOne(Mapel::className(), ['mapel_id' => 'fk_mapel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiswa() {
        return $this->hasOne(Siswa::className(), ['siswa_id' => 'fk_siswa_id']);
    }
}

models/Kelas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "dst_kelas".
 *
 * @property string $kelas_id
 * @property string $kelas_kode
 * @property integer $kelas_grade
 * @property integer $kelas_semester
 * @property string $fk_user_id
 *
 * @property Absen[] $dstAbsens
 * @property User $fkUser
 * @property Keuangan[] $dstKeuangans
 * @property Nilai[] $dstNilais
 * @property Siswa[] $dstSiswas
 */
class Kelas extends \yii\db\ActiveRecord {
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'dst_kelas';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['kelas_kode', 'kelas_grade', 'kelas_semester', 'fk_user_id'], 'required'],
            [['kelas_grade', 'kelas_semester', 'fk_user_id'], 'integer'],
            [['kelas_kode'], 'string', 'max' => 21],
            [['kelas_kode', 'kelas_grade', 'kelas_semester'], 'unique', 'targetAttribute' => ['kelas_kode', 'kelas_grade', 'kelas_semester'], 'message' => 'The combination of Kelas Kode, Kelas Grade and Kelas Semester has already been taken.'],
            [['fk_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['fk_user_id' => 'user_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'kelas_id' => 'Kelas ID',
            'kelas_kode' => 'Kode Kelas',
            'kelas_grade' => 'Grade Kelas',
            'kelas_semester' => 'Semester',
            'fk_user_id' => 'Wali Kelas',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAbsens() {
        return $this->hasMany(Absen::className(), ['fk_kelas_id' => 'kelas_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser() {
        return $this->hasOne(User::className(), ['user_id' => 'fk_user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKeuangans() {
        return $this->hasMany(Keuangan::className(), ['fk_kelas_id' => 'kelas_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNilais() {
        return $this->hasMany(Nilai::className(), ['fk_kelas_id' => 'kelas_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiswas() {
        return $this->hasMany(Siswa::className(), ['fk_kelas_id' => 'kelas_id']);
    }
}

controllers/AbsenController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Absen;
use app\models\AbsenSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AbsenController implements the CRUD actions for Absen model.
 */
class AbsenController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Absen models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AbsenSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Absen model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Absen model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Absen();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->absen_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Absen model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->absen_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Absen model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Absen model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Absen the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Absen::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/absen/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;
use app\models\Siswa;
use app\models\Kelas;
use app\models\Jurusan;
use app\models\Mapel;

/* @var $this yii\web\View */
/* @var $model app\models\Absen */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="absen-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'fk_siswa_id')->dropDownList(ArrayHelper::map(Siswa::find()->all(), 'siswa_id', 'siswa_nama'), ['prompt' => 'Select Siswa']) ?>

    <?= $form->field($model, 'fk_kelas_id')->dropDownList(ArrayHelper::map(Kelas::find()->all(), 'kelas_id', 'kelas_kode'), ['prompt' => 'Select Kelas']) ?>

    <?= $form->field($model, 'fk_jurusan_id')->dropDownList(ArrayHelper::map(Jurusan::find()->all(), 'jurusan_id', 'jurusan_nama'), ['prompt' => 'Select Jurusan']) ?>

    <?= $form->field($model, 'fk_mapel_id')->dropDownList(ArrayHelper::map(Mapel::find()->all(), 'mapel_id', 'mapel_nama'), ['prompt' => 'Select Mata Pelajaran']) ?>

    <?= $form->field($model, 'absen_keterangan')->dropDownList(['Hadir' => 'Hadir', 'Ijin' => 'Ijin', 'Sakit' => 'Sakit', 'Alpa' => 'Alpa',], ['prompt' => 'Select Kehadiran']) ?>

    <?= $form->field($model, 'absen_tanggal')->widget(DatePicker::className(), [
        'dateFormat' => 'yyyy-MM-dd',
        'clientOptions' => [
            'changeMonth' => true,
            'changeYear' => true,
        ],
        'options' => [
            'class' => 'form-control',
            'readOnly' => 'readOnly',
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/absen/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AbsenSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="absen-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'absen_id') ?>

    <?= $form->field($model, 'fk_siswa_id') ?>

    <?= $form->field($model, 'fk_kelas_id') ?>

    <?= $form->field($model, 'fk_jurusan_id') ?>

    <?= $form->field($model, 'fk_mapel_id') ?>

    <?php // echo $form->field($model, 'absen_keterangan') ?>

    <?php // echo $form->field($model, 'absen_tanggal') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/absen/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Absen */

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => 'Absensi', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="absen-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/absen/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AbsenSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Absensi';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="absen-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Yii::$app->user->identity->fk_hak_id != 2 ? Html::a('Create', ['create'], ['class' => 'btn btn-success']) : '' ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'absen_id',
            [
                'attribute' => 'fk_siswa_id',
                'value' => 'siswa.siswa_nama',
            ],
            [
                'attribute' => 'fk_kelas_id',
                'value' => 'kelas.kelas_kode',
            ],
            [
                'attribute' => 'fk_jurusan_id',
                'value' => 'jurusan.jurusan_nama',
            ],
            [
                'attribute' => 'fk_mapel_id',
                'value' => 'mapel.mapel_nama',
            ],
            'absen_keterangan',
            'absen_tanggal',

            [
                'class' => 'yii\grid\ActionColumn',
                'visibleButtons' => [
                    'update' => function ($model, $key, $index) {
                        return Yii::$app->user->identity->fk_hak_id != 2 ? true : false;
                    },
                    'delete' => function ($model, $key, $index) {
                        return Yii::$app->user->identity->fk_hak_id != 2 ? true : false;
                    }
                ]
            ],
        ],
    ]); ?>
</div>

views/absen/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Absen */

$this->title = 'Update : ' . $model->absen_id;
$this->params['breadcrumbs'][] = ['label' => 'Absensi', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->absen_id, 'url' => ['view', 'id' => $model->absen_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="absen-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/absen/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Absen */

$this->title = $model->absen_id;
$this->params['breadcrumbs'][] = ['label' => 'Absensi', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="absen-view">

    <p>
        <?= Yii::$app->user->identity->fk_hak_id != 2 ? Html::a('Update', ['update', 'id' => $model->absen_id], ['class' => 'btn btn-primary']) : '' ?>
        <?= Yii::$app->user->identity->fk_hak_id != 2 ? Html::a('Delete', ['delete', 'id' => $model->absen_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) : '' ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'absen_id',
            [
                'attribute' => 'fk_siswa_id',
                'value' => $model->siswa->siswa_nama,
            ],
            [
                'attribute' => 'fk_kelas_id',
                'value' => $model->kelas->kelas_kode,
            ],
            [
                'attribute' => 'fk_jurusan_id',
                'value' => $model->jurusan->jurusan_nama,
            ],
            [
                'attribute' => 'fk_mapel_id',
                'value' => $model->mapel->mapel_nama,
            ],
            'absen_keterangan',
            'absen_tanggal',
        ],
    ]) ?>

</div>